# Generated by Django 5.1 on 2024-09-09 18:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Shreesh Tiwari (Default)', max_length=200, null=True)),
                ('title', models.CharField(default='This is default title, change it in profile.', max_length=200, null=True)),
                ('desc', models.CharField(default="Hey, there text description about you that you can change after clicking on 'Edit'", max_length=200, null=True)),
                ('profile_img', models.ImageField(blank=True, default='images/default.jpg', null=True, upload_to='images')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
