# Generated by Django 5.1 on 2024-09-16 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_aboutcategory_contact_socialmediatitle_about_and_more'),
        ('courses', '0004_aboutcategory_contact_socialmediatitle_and_more'),
    ]

    operations = [
    ]
