# Generated by Django 5.1 on 2024-09-16 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_allabout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponcode',
            name='expiry_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='couponcode',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
